---
- name: Run commands on Win
  hosts: windows
  gather_facts: false
  
  tasks:
  - name: Replace SNMP communities and managers
    win_snmp:
      community_strings:
        - sunhose
      permitted_managers:
        - 192.168.1.202
        - localhost
      action: set
    register: result

  - name: PRINT TO TERMINAL WINDOW
    debug:
      msg: "{{result}}"

#  - name: Debug
#    debug: var=result.stdout_lines