- name: Install AWS CLI
  hosts: all 
  vars: 
    aws_cli_download_dir: c:\downloads
    aws_cli_msi_url: https://s3.amazonaws.com/aws-cli/AWSCLI32PY3.msi
  tasks:
    - name: Ensure target directory exists
      win_file:
        path: "{{ aws_cli_download_dir }}"
        state: directory
    - name: Download installer
      win_get_url: 
        url: "{{ aws_cli_msi_url }}"
        dest: "{{ aws_cli_download_dir }}\\awscli.msi"
        force: no
    - name: Install AWS CLI
      win_package:
        path: "{{ aws_cli_download_dir }}\\awscli.msi"
        state: present