1. Построение контейнеров c Dockerfile.

Dockerfile:
##################################
FROM docker.io/fedora:29 
 
RUN dnf install -y cowsay nginx 
RUN echo "daemon off;" >> /etc/nginx/nginx.conf 
RUN cowsay boop > /usr/share/nginx/html/index.html 
 
EXPOSE 80 
 
CMD /usr/sbin/nginx
##################################

--- 
- name: build an image 
  hosts: localhost 
  gather_facts: false 
 
  tasks: 
    - name: build that image 
      docker_image: 
        path: . 
        state: present 
        name: fedora-moo 
 
    - name: start the container 
      docker_container: 
        name: playbook-container 
        image: fedora-moo 
        ports: 8080:80 
        state: started
 	   
##################################
No root: curl http://localhost:8080               
##################################

2. Построение контейнеров без Dockerfile.

---
- name: build an image
  hosts: localhost
  gather_facts: false

  tasks:
    - name: start the container
      docker_container:
        name: playbook-container
        image: docker.io/fedora:29
        ports: 8080:80
        state: started
        command: sleep 500

    - name: make a host
      add_host:
        name: playbook-container
        ansible_connection: docker
        ansible_ssh_user: root

- name: do things
  hosts: playbook-container
  gather_facts: false

  tasks:
    - name: install things
      raw: dnf install -y python-dnf

    - name: install things
      dnf:
        name: ['nginx', 'cowsay']

    - name: configure nginx
      lineinfile:
        line: "daemon off;"
        dest: /etc/nginx/nginx.conf

    - name: boop
      shell: cowsay boop > /usr/share/nginx/html/index.html

    - name: run nginx
      shell: nginx &
 	    	   