---
- name: Linux system reboot
  hosts: test
  become: yes

  tasks:
 
  - name: Reboot host
    command: shutdown -r now "Ansible system reboot"
    async: 1
    poll: 0

  - name: Wait for the host to finish rebooting
    local_action: wait_for host={{ inventory_hostname }} state=started
    become: false
    delegate_to: localhost

OR

  - name: Wait for the host to finish rebooting
    wait_for:
        host: "{{ inventory_hostname }}"
        state: started
        delay: 5
        timeout: 40
    delegate_to: localhost


"To launch a task asynchronously, specify its maximum runtime and how frequently you would like to poll for status."

1) async - говорит о том, что команду надо запустить асинхронно, т.е. продолжить выполнение плейбука после ее запуска не дожидаясь ответа. 
Значение указанное тут, говорит о таймауте на время выполнения (сессии ssh ??).

2) poll - говорит о том, через сколько попробовать получить результат выполнения команды. Рoll = 0 говорит что результат не нужен.